# Generated by Django 3.1.1 on 2020-09-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_tags_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='code',
            field=models.CharField(max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
